# Generated by Django 4.2.5 on 2024-01-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0105_alter_formdata_district_alter_formdata_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='defName', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='formdata',
            name='num_of_people',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='formdata',
            name='people_names',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formdata',
            name='people',
            field=models.ManyToManyField(related_name='entries', to='main.person'),
        ),
    ]
