# Generated by Django 4.2.5 on 2024-01-26 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0107_alter_person_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdata',
            name='people',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
