# Generated by Django 4.2.5 on 2024-01-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0108_remove_formdata_people_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='people_names',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
