# Generated by Django 4.2.5 on 2024-01-27 09:21

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0110_delete_appsetting_remove_assignsubscriber_trainer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='id_number',
            field=models.CharField(max_length=10, validators=[main.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='name',
            field=models.CharField(default='Name Surname', max_length=100),
        ),
    ]
