# Generated by Django 4.2.5 on 2024-01-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0111_alter_formdata_id_number_alter_formdata_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='num_of_people',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
