# Generated by Django 4.2.5 on 2024-01-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0112_alter_formdata_num_of_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='display_num_of_people',
            field=models.BooleanField(default=False),
        ),
    ]
