# Generated by Django 4.2.5 on 2024-01-27 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0113_formdata_display_num_of_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formdata',
            old_name='display_num_of_people',
            new_name='additional_people',
        ),
        migrations.RenameField(
            model_name='formdata',
            old_name='people_names',
            new_name='additional_people_names',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='num_of_people',
        ),
    ]
