# Generated by Django 4.2.5 on 2024-01-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0114_rename_display_num_of_people_formdata_additional_people_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='has_vehicle',
            field=models.BooleanField(default=False),
        ),
    ]
