# Generated by Django 4.2.5 on 2024-01-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0115_alter_formdata_has_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='id_number',
            field=models.CharField(max_length=100),
        ),
    ]
