# Generated by Django 4.2.5 on 2024-01-29 05:11

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0116_alter_formdata_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='id_number',
            field=models.CharField(max_length=10, validators=[main.models.validate_phone_number]),
        ),
    ]
