# Generated by Django 4.2.5 on 2024-01-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0117_alter_formdata_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='district',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='province',
            field=models.CharField(max_length=20),
        ),
    ]
