# Generated by Django 4.2.5 on 2024-01-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0119_alter_formdata_district_alter_formdata_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='id_number',
            field=models.CharField(max_length=100),
        ),
    ]
