# Generated by Django 4.2.5 on 2024-05-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0121_alter_formdata_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='current_status',
            field=models.CharField(blank=True, choices=[('Pass Issued', 'Pass Issued'), ('Entered', 'Entered'), ('Exited', 'Exited')], default='Pass Issued', max_length=100),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='date_of_entry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='purpose',
            field=models.CharField(default='Official', max_length=100),
        ),
    ]
