# Generated by Django 4.2.5 on 2024-05-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0122_alter_formdata_current_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='date_of_entry',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
