# Generated by Django 4.2.5 on 2024-05-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0123_alter_formdata_date_alter_formdata_date_of_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='date_of_exit',
            field=models.CharField(blank=True, null=True),
        ),
    ]
