# Generated by Django 4.2.5 on 2024-06-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0124_alter_formdata_date_of_exit'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='num_of_add_people',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
