# Generated by Django 4.2.5 on 2024-06-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0125_formdata_num_of_add_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='assigned_office',
            field=models.CharField(blank=True, default='User', max_length=100),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='group',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='purpose',
            field=models.CharField(max_length=100),
        ),
    ]
