# Generated by Django 4.2.5 on 2024-07-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0126_formdata_assigned_office_alter_formdata_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='assigned_office',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='num_of_add_people',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
