# Generated by Django 4.2.5 on 2024-07-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0127_alter_formdata_assigned_office_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='other_purpose',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
